-- =============================================================================
-- CODEship Academy — Builders Quiz Questions Q37–Q50
-- =============================================================================

-- =============================================================================
-- Q37: Scratch Broadcasting Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q37', 'What does the "broadcast" block do in Scratch?', '["Plays a sound","Sends a message to all sprites","Deletes a sprite","Changes the backdrop"]', 1, 'Broadcast sends a message that any sprite can listen for using "when I receive", letting sprites talk to each other.', 1),
  ('bld-q37', 'Which block lets a sprite respond to a broadcasted message?', '["when this sprite clicked","when I receive","when green flag clicked","when key pressed"]', 1, 'The "when I receive" block triggers a sprite''s scripts when it hears a specific broadcast message.', 2),
  ('bld-q37', 'What is the difference between "broadcast" and "broadcast and wait"?', '["There is no difference","Broadcast and wait pauses the script until receivers finish","Broadcast and wait only works on backdrops","Broadcast and wait deletes the message after sending"]', 1, '"Broadcast and wait" pauses the sending script until all scripts triggered by that message have finished running.', 3),
  ('bld-q37', 'Why are broadcasts useful for coordinating multiple sprites?', '["They make sprites move faster","They let separate scripts react to the same event at the same time","They automatically change sprite costumes","They delete unused sprites"]', 1, 'Broadcasts act like an announcement that many sprites can hear at once, so they can all react together without being directly connected.', 4),
  ('bld-q37', 'You want a "Game Over" message to appear only after the player loses. What is a good approach?', '["Use a forever loop with no conditions","Broadcast a \"game over\" message when the lose condition is met, and have the message sprite listen for it","Type the words directly into the stage backdrop","Delete the player sprite immediately"]', 1, 'Broadcasting "game over" at the right moment lets a separate sprite or backdrop respond by showing the message, keeping code organized.', 5),
  ('bld-q37', 'Can you create your own custom broadcast message names in Scratch?', '["No, only \"message1\" is allowed","Yes, you can name broadcasts anything you want, like \"startLevel2\"","No, broadcasts are randomly named by Scratch","Yes, but only numbers are allowed as names"]', 1, 'Scratch lets you create and name new broadcast messages so your code stays clear and organized, like "startLevel2" or "playerHit".', 6),
  ('bld-q37', 'If three different sprites all have a "when I receive: jump" script, what happens when "jump" is broadcast?', '["Only the first sprite responds","Nothing happens unless they are touching","All three sprites run their \"jump\" scripts at the same time","Only the last sprite created responds"]', 2, 'Every sprite listening for that specific message runs its matching script when the broadcast happens, no matter how many sprites are listening.', 7),
  ('bld-q37', 'Which scenario is the BEST use of broadcasting?', '["Changing one sprite''s color by itself","Telling all enemy sprites to start moving when the player presses start","Adding two numbers together","Drawing a single line with the pen tool"]', 1, 'Broadcasting shines when one event needs to trigger actions across multiple sprites, like starting all enemies at once.', 8),
  ('bld-q37', 'What happens if a broadcast message is sent but no sprite has a matching "when I receive" block?', '["Scratch crashes","The project deletes the message","Nothing happens — the broadcast is simply ignored","All sprites disappear"]', 2, 'If nothing is listening for a broadcast, it just has no effect; Scratch does not produce an error.', 9),
  ('bld-q37', 'In a multiplayer-style Scratch game, broadcasting "resetGame" to all sprites is useful because it', '["lets every sprite reset its position and variables at the same moment","only resets the backdrop","stops the project completely","saves the project to the cloud"]', 0, 'A "resetGame" broadcast lets every sprite run its own reset script simultaneously, keeping the whole game in sync.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q38: Scratch Platform Games Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q38', 'In a platform game, what does "gravity" usually mean in Scratch code?', '["The sprite changes color over time","A constant downward pull added to the sprite''s y-position each frame","The sprite gets bigger","The background scrolls sideways"]', 1, 'Gravity is simulated by repeatedly decreasing the sprite''s y-position (or vertical speed) so it falls unless something stops it.', 1),
  ('bld-q38', 'How do you usually detect if a sprite is standing on a platform?', '["Check if the sprite''s costume number is even","Use \"touching [platform]?\" to see if the sprite is in contact with the platform","Check the sprite''s name","Use the \"ask\" block"]', 1, 'The "touching" block checks for contact between sprites, which is how platform games detect if a character is standing on solid ground.', 2),
  ('bld-q38', 'What is a common way to make a character jump in Scratch?', '["Change x by a large negative number","Set a vertical speed variable to a positive number, then let gravity pull it back down","Use the \"say\" block","Delete and recreate the sprite"]', 1, 'Jumping is often coded by giving the sprite an upward speed value that gravity gradually reduces, creating a smooth arc.', 3),
  ('bld-q38', 'Why do platform games usually check "if key pressed" inside a forever loop?', '["To constantly check whether the player wants to move or jump","To slow down the game","To delete old scripts","To change the backdrop randomly"]', 0, 'A forever loop with key-press checks lets the game respond instantly and continuously to player input.', 4),
  ('bld-q38', 'What could cause a platform character to "fall through" a platform in Scratch?', '["The costume is too colorful","Collision detection isn''t checked often enough or the platform is too thin","The sprite has too many variables","The stage is too big"]', 1, 'If the game doesn''t check collisions frequently enough, or the platform shape is too thin, a fast-moving sprite can pass through it before the check happens.', 5),
  ('bld-q38', 'What is the purpose of a "variable" called something like "yVelocity" in a platformer?', '["It stores the sprite''s name","It tracks how fast the sprite is moving up or down","It counts how many sprites exist","It stores the backdrop color"]', 1, 'A velocity variable tracks speed and direction, which is essential for realistic jumping and falling motion.', 6),
  ('bld-q38', 'In a platform game, what usually happens when the player''s sprite touches a "spike" or "enemy" sprite?', '["The game saves automatically","Something negative happens, like losing a life or restarting the level","The sprite turns into the enemy","Nothing, hazards are decorative"]', 1, 'Touching hazards typically triggers a penalty like losing a life, taking damage, or restarting, which is core platformer gameplay.', 7),
  ('bld-q38', 'Why might a platform game use multiple costumes for the player sprite?', '["To confuse the player","To show animations like walking, jumping, and standing still","To make the file size smaller","Costumes are required by Scratch and have no purpose"]', 1, 'Switching costumes creates the illusion of movement, such as walking or jumping animations, making the game feel alive.', 8),
  ('bld-q38', 'What does "if on edge, bounce" do, and is it typically used in platformers?', '["It makes the sprite bounce off stage edges; it is more common in pong-style games than platformers","It deletes the sprite at the edge","It changes the backdrop","It pauses the whole game"]', 0, '"If on edge, bounce" reverses direction at the stage border—useful for bouncing balls, but platformers usually need custom edge and platform logic instead.', 9),
  ('bld-q38', 'What is a "checkpoint" in a platform game, and why is it useful?', '["A place where the player must stop forever","A saved position the player respawns at after losing a life, instead of restarting the whole level","A type of enemy","A decoration with no gameplay effect"]', 1, 'Checkpoints let players continue from a recent point instead of restarting the entire level, making the game more enjoyable.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q39: Scratch Cloning Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q39', 'What does "create clone of myself" do in Scratch?', '["Deletes the current sprite","Makes a temporary copy of the sprite that runs its own scripts","Changes the sprite''s costume","Pauses the program"]', 1, 'This block creates a new, temporary copy of a sprite, which can run "when I start as a clone" scripts independently.', 1),
  ('bld-q39', 'Which block runs code specifically for a newly created clone?', '["when green flag clicked","when I start as a clone","when this sprite clicked","when I receive"]', 1, '"When I start as a clone" is the hat block that triggers scripts only for clones, separate from the original sprite''s scripts.', 2),
  ('bld-q39', 'Why is cloning useful for making lots of bullets or enemies in a game?', '["It lets you reuse one sprite''s code to create many copies instead of making separate sprites","It automatically wins the game","It changes the backdrop color","It deletes the original sprite"]', 0, 'Cloning lets one sprite generate many copies dynamically, which is much more efficient than manually creating dozens of similar sprites.', 3),
  ('bld-q39', 'What does "delete this clone" do?', '["Deletes the original sprite permanently","Removes just that one clone from the project while it''s running","Deletes all clones of every sprite","Pauses the clone instead of removing it"]', 1, '"Delete this clone" removes only the specific clone running that script, which helps prevent clutter and keeps performance smooth.', 4),
  ('bld-q39', 'What happens if you never delete clones in a game with constant cloning, like a bullet-spawner?', '["Nothing, Scratch deletes them automatically after 10 seconds","The game can slow down or hit Scratch''s clone limit","The backdrop changes color","The sprite becomes invisible"]', 1, 'Without cleanup, clones pile up, which can slow down the project or hit Scratch''s maximum clone limit (300), causing problems.', 5),
  ('bld-q39', 'Do clones inherit the scripts of the original sprite?', '["No, clones have no scripts at all","Yes, clones run the same scripts as the original, including \"when I start as a clone\"","Only \"when green flag clicked\" scripts are copied","Clones only inherit costumes, not code"]', 1, 'Clones automatically have all the same scripts as their original sprite and can run "when I start as a clone" independently.', 6),
  ('bld-q39', 'In a game where stars rain down from the top of the screen, what is a good use of cloning?', '["Clone the star sprite repeatedly and have each clone fall and delete itself off-screen","Create 50 separate star sprites by hand","Use the \"ask\" block to ask for stars","Only use one star and move it back and forth"]', 0, 'Cloning is perfect here: one star sprite can repeatedly clone itself, with each clone falling independently and deleting itself when off-screen.', 7),
  ('bld-q39', 'What is a typical way to give each clone slightly different behavior, like a random starting position?', '["Clones cannot have different behavior","Use \"when I start as a clone\" combined with \"go to random position\" or random number blocks","Edit each clone''s code by hand","Use the \"stop all\" block"]', 1, 'Inside "when I start as a clone," using random position or random number blocks gives each clone unique starting behavior.', 8),
  ('bld-q39', 'How is a "clone" different from a regular new sprite you drag into the project?', '["A clone is a temporary copy created and controlled by code while the project runs; a new sprite is added manually in the editor","There is no difference","Clones can only be backdrops","New sprites are deleted when the game starts"]', 0, 'Clones are made dynamically through code while the program is running, whereas sprites are added manually in the Scratch editor before running.', 9),
  ('bld-q39', 'Why might a developer check "if touching player" inside a clone''s forever loop in an enemy-spawning game?', '["To rename the clone","To detect when that specific clone hits the player and trigger an action, like losing a life","To create more clones","To change the backdrop music"]', 1, 'Each clone can independently check its own collisions, so the game can react appropriately whenever any individual clone touches the player.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q40: Scratch Quiz Games Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q40', 'Which Scratch block lets a sprite ask the player a question and wait for typed input?', '["say","ask and wait","think","broadcast"]', 1, 'The "ask and wait" block displays a question and a text box, pausing the script until the player types an answer.', 1),
  ('bld-q40', 'Where does the player''s typed response from "ask and wait" get stored?', '["In the \"answer\" variable","In the \"score\" variable","It is not stored anywhere","In the backdrop name"]', 0, 'Scratch automatically stores whatever the player types into a special built-in variable called "answer".', 2),
  ('bld-q40', 'How would you check if the player''s answer to a quiz question is correct?', '["Use an \"if/then\" block comparing the \"answer\" variable to the correct text","Use the \"pen down\" block","Use the \"go to\" block","There is no way to check answers in Scratch"]', 0, 'An "if answer = [correct text] then" block compares what the player typed to the expected correct answer.', 3),
  ('bld-q40', 'In a quiz game, what is a "score" variable typically used for?', '["Tracking how many questions the player has answered correctly","Storing the backdrop name","Counting how many sprites exist","Changing the language of the quiz"]', 0, 'A score variable keeps track of correct answers (or points) so the player can see how well they performed.', 4),
  ('bld-q40', 'Why is it helpful to use a "change score by 1" block inside an "if correct answer" check?', '["It deletes the sprite","It increases the score only when the player answers correctly","It changes the backdrop color","It restarts the whole project"]', 1, 'Placing "change score by 1" inside the correct-answer condition means points are only added when the player actually gets it right.', 5),
  ('bld-q40', 'What is a common way to present multiple-choice options in a Scratch quiz?', '["Use \"say\" blocks to show each choice and \"ask and wait\" for the player to type the letter or number of their choice","Multiple choice is impossible in Scratch","Use only true/false questions","Use the pen tool to draw answers"]', 0, 'Many Scratch quizzes display options with "say" or on-screen text, then use "ask and wait" so players type their chosen letter or number.', 6),
  ('bld-q40', 'Why might a quiz game use a list (like "questions" and "answers") instead of hardcoding every question separately?', '["Lists make the game slower","Lists let you organize many questions and loop through them efficiently","Lists are required by Scratch","Lists only work with numbers"]', 1, 'Using lists lets you store many questions and answers together and loop through them with code, avoiding repetitive duplicated scripts.', 7),
  ('bld-q40', 'How could a quiz game tell the player their final score at the end?', '["Use a \"say\" block with \"join\" to combine text and the score variable","Delete the score variable","Only show the score as a costume change","Quizzes cannot display a final score"]', 0, 'Combining "join" with the score variable inside a "say" block lets the sprite display a custom message like "You got 7 points!"', 8),
  ('bld-q40', 'What happens if the comparison in "if answer = correctAnswer" is case-sensitive and the player types "Paris" but the answer is stored as "paris"?', '["It always matches regardless of case","In Scratch, the \"=\" operator is not case-sensitive, so it would still match","The game crashes","The score is automatically doubled"]', 1, 'Scratch''s equality operator ignores letter case, so "Paris" and "paris" are treated as the same answer.', 9),
  ('bld-q40', 'Why is feedback (like "Correct!" or "Try again!") important in a quiz game?', '["It is not important and can be skipped","It helps players know immediately whether their answer was right, making the game more engaging and educational","It slows down the game unnecessarily","It only matters for the last question"]', 1, 'Immediate feedback helps players learn from mistakes and stay engaged, which is a key part of good educational game design.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q41: Scratch Animation Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q41', 'What is the basic idea behind animation in Scratch?', '["Quickly switching between costumes to create the illusion of movement","Changing the project''s language","Deleting and recreating sprites","Using only sound blocks"]', 0, 'Animation works by rapidly switching a sprite''s costumes, similar to a flipbook, which tricks the eye into seeing motion.', 1),
  ('bld-q41', 'Which block is commonly used to cycle through a sprite''s costumes for a walking animation?', '["next costume","change color effect","go to front","set rotation style"]', 0, '"Next costume" advances to the following costume in the sprite''s list, which is the basis of frame-by-frame animation.', 2),
  ('bld-q41', 'Why do animators usually add a small "wait" (like 0.1 seconds) between costume changes?', '["To slow the animation down to a smooth, watchable speed instead of an instant blur","To save battery life","To make the sprite disappear","Wait blocks are required by Scratch and do nothing else"]', 0, 'Without a short wait, costume changes would happen too fast to see clearly, so a small delay paces the animation naturally.', 3),
  ('bld-q41', 'What does the "glide" block do that makes animation look smoother than "go to x: y:"?', '["It moves the sprite gradually over time instead of teleporting instantly","It changes costumes automatically","It deletes the sprite after moving","It only works with backdrops"]', 0, '"Glide" moves a sprite smoothly across the stage over a set duration, while "go to" jumps the sprite instantly to a new position.', 4),
  ('bld-q41', 'In Scratch, what is the difference between a "costume" and a "backdrop"?', '["A costume is a sprite''s appearance; a backdrop is the background image of the stage","They are the same thing","A backdrop is a type of sound","A costume only applies to text sprites"]', 0, 'Costumes belong to individual sprites and change their appearance, while backdrops are images that set the scene behind all sprites.', 5),
  ('bld-q41', 'How can you make a flying bird sprite flap its wings while also moving across the screen?', '["Combine a costume-cycling animation loop with movement blocks like \"change x by\" running together","Only use the \"say\" block","Animation and movement cannot happen at the same time","Use a single static costume"]', 0, 'Running an animation loop (cycling costumes) alongside a movement script lets a sprite both flap and travel across the stage simultaneously.', 6),
  ('bld-q41', 'What does the "set rotation style" block control?', '["How a sprite turns: normally rotating, only left-right flipping, or not rotating at all","The sprite''s color","The sprite''s sound volume","The backdrop''s rotation"]', 0, 'Rotation style determines whether a sprite spins fully, flips left-right only, or stays fixed regardless of its direction, which matters for natural-looking animation.', 7),
  ('bld-q41', 'Why might "left-right" rotation style be better than "all around" for a walking character sprite?', '["It prevents the character from looking upside-down when facing left","It makes the sprite invisible","It is required for all sprites","It disables costume changes"]', 0, 'With "all around" rotation, a character facing left could appear flipped upside-down; "left-right" only mirrors the image, keeping it upright and natural.', 8),
  ('bld-q41', 'What is a simple way to animate a bouncing ball going up and down repeatedly?', '["Use a forever loop that changes y by a positive then negative amount with waits in between","Use the \"ask and wait\" block","Delete the ball sprite each bounce","Change the ball''s costume to a different sprite"]', 0, 'A forever loop alternating between moving the y-position up and down (with brief waits) creates a simple, repeating bounce animation.', 9),
  ('bld-q41', 'Why is it helpful to preview your animation costumes in order before adding code?', '["It is not helpful at all","It helps you confirm the costumes flow smoothly frame-to-frame before wiring up the animation logic","Scratch requires previewing before saving","It changes the costume file names"]', 1, 'Checking that costumes are in a sensible order ahead of time helps ensure the animation will look smooth once the code cycles through them.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q42: Scratch Stories Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q42', 'Which Scratch block is most commonly used to show a character''s dialogue in a story?', '["say","move","wait","broadcast"]', 0, 'The "say" block displays text in a speech bubble above the sprite, which is the main way stories show character dialogue.', 1),
  ('bld-q42', 'What is the difference between "say" and "say for 2 seconds"?', '["No difference at all","\"Say\" stays until changed or cleared, while \"say for 2 seconds\" automatically disappears after the timer","Say for 2 seconds repeats forever","Say only works with numbers"]', 1, '"Say" keeps the speech bubble visible until another block changes or clears it, while "say for 2 seconds" automatically removes the bubble after the given time.', 2),
  ('bld-q42', 'In an interactive story, why might you use broadcasts to move between scenes?', '["Broadcasts can signal all relevant sprites and backdrops to update together for the next scene","Broadcasts only affect sound","Broadcasts delete all sprites","Broadcasts are not allowed in stories"]', 0, 'Broadcasting a "scene2" message, for example, lets the backdrop change and the right sprites appear/disappear together in sync.', 3),
  ('bld-q42', 'How can you make a story branch based on a choice the reader makes?', '["Use \"ask and wait\" for input, then \"if/else\" blocks to change what happens next","Stories cannot have branches in Scratch","Only use the \"wait\" block","Branching requires deleting sprites"]', 0, 'Asking the reader a question and then using if/else logic on their answer allows the story to take different paths, like a choose-your-own-adventure.', 4),
  ('bld-q42', 'What is a good way to control the order in which characters speak in a scene?', '["Use \"wait\" blocks or broadcasts so one character finishes talking before the next one starts","Have every character say their line at the exact same time","Order doesn''t matter in Scratch stories","Use the pen tool"]', 0, 'Sequencing speech with waits or broadcast/receive chains ensures dialogue happens in the right order rather than all sprites talking simultaneously.', 5),
  ('bld-q42', 'Why might you change the backdrop between different parts of a story?', '["To represent a new scene or location, like moving from a forest to a castle","Backdrops cannot be changed during a project","To slow down the program","To delete unused sprites"]', 0, 'Changing the backdrop visually signals a new setting or chapter in the story, helping the audience follow the plot.', 6),
  ('bld-q42', 'What block would you use to make a sprite disappear when it leaves a scene, and reappear later?', '["hide and show","delete this sprite","change costume to","go to front layer"]', 0, '"Hide" and "show" let a sprite become invisible and then visible again without deleting it, which is useful for characters entering and exiting scenes.', 7),
  ('bld-q42', 'In a story project, what is the benefit of using separate scripts triggered by "when I receive [scene name]" for each character?', '["It keeps each character''s actions organized and synced to the right part of the story","It is unnecessary and never used","It makes the story slower","It only works for backgrounds"]', 0, 'Organizing each character''s reactions by scene-specific broadcasts keeps the project clean and ensures everyone acts at the correct story moment.', 8),
  ('bld-q42', 'Why is pacing (using "wait" blocks between lines of dialogue) important in a Scratch story?', '["It gives the reader time to read each line before it changes, making the story easier to follow","Pacing has no effect on storytelling","It is only used to slow down animations","Wait blocks delete dialogue"]', 0, 'Without pauses, dialogue could change too fast to read, so wait blocks help the audience comfortably follow the story.', 9),
  ('bld-q42', 'What is one way to give your story an interactive ending where the audience''s choice changes the outcome?', '["Use \"ask and wait\" near the end and branch with if/else to show different endings based on the response","Endings must always be the same in Scratch","Use the pen tool to draw the ending","Endings cannot use variables"]', 0, 'Capturing reader input near the climax and branching the result with if/else creates multiple possible endings, increasing engagement.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q43: CSS Clip-Path Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q43', 'What does the CSS "clip-path" property do?', '["Changes text color","Cuts an element into a visible shape, hiding everything outside that shape","Adds a shadow to an element","Changes the font size"]', 1, 'Clip-path defines a visible region for an element — anything outside the clipping shape is hidden, letting you create custom shapes from rectangular elements.', 1),
  ('bld-q43', 'Which clip-path shape function creates a circular cutout?', '["circle()","square()","round()","ellipse-only()"]', 0, 'The circle() function defines a circular clipping region, commonly used with a radius and center position like circle(50%).', 2),
  ('bld-q43', 'What does clip-path: polygon() let you do?', '["Add multiple background images","Define a custom shape using a list of x,y coordinate points","Animate text color","Create a circle only"]', 1, 'polygon() takes a series of coordinate points to create custom multi-sided shapes, like triangles, stars, or arrows.', 3),
  ('bld-q43', 'If you apply clip-path: circle(50%) to a square image, what will it look like?', '["A square with rounded corners","A perfect circle cut from the image","No visual change at all","The image disappears completely"]', 1, 'circle(50%) clips the image into a circular shape using 50% as the radius relative to the element''s size, producing a circular crop.', 4),
  ('bld-q43', 'Why might a web developer use clip-path instead of just making an image file already shaped like a triangle?', '["clip-path lets you keep the original image and dynamically change its shape with CSS, no image editing needed","clip-path is required for all images","Image files can never be shaped","There is no real benefit"]', 0, 'Clip-path applies shaping directly in CSS, so you can adjust or animate the shape without needing to edit or replace the image file.', 5),
  ('bld-q43', 'What units can be used inside clip-path shape functions like polygon()?', '["Only pixels","Percentages and length units like px, both are valid","Only percentages","Only colors"]', 1, 'Clip-path coordinates can be written in percentages or absolute length units like pixels, giving flexibility for responsive design.', 6),
  ('bld-q43', 'What happens to the parts of an element outside the clip-path shape?', '["They turn white","They become completely hidden from view, as if cut away","They get a border","They move to a new position"]', 2, 'Anything outside the defined clip-path region is hidden, similar to using scissors to cut around a shape and discard the rest.', 7),
  ('bld-q43', 'Which is a realistic creative use of clip-path on a website?', '["Creating a diagonal-cut hero image section for visual interest","Changing the page''s language","Validating a form","Connecting to a database"]', 0, 'Clip-path is popular for creative layout effects, such as angled section dividers or custom-shaped image cutouts, adding visual interest to designs.', 8),
  ('bld-q43', 'Can clip-path shapes be animated with CSS transitions?', '["No, clip-path can never be animated","Yes, you can transition between different clip-path shapes for animated effects","Only circle() can be animated","Animations require JavaScript and clip-path cannot use CSS transitions at all"]', 1, 'Clip-path values can be transitioned in modern browsers, enabling fun effects like a shape growing, shrinking, or morphing on hover.', 9),
  ('bld-q43', 'If you wanted to clip an element into a triangle pointing upward, which clip-path function would you use?', '["circle()","ellipse()","inset()","polygon() with three coordinate points"]', 3, 'A triangle requires exactly three points, so polygon() with three x,y coordinates is the correct tool to create that shape.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q44: CSS Position Advanced Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q44', 'What does "position: relative" do to an element by itself, with no top/left/right/bottom set?', '["Moves it far off the page","Nothing visually changes, but it becomes a reference point for child elements with \"position: absolute\"","Deletes the element","Makes it transparent"]', 1, 'On its own, relative positioning doesn''t move the element, but it establishes a positioning context for any absolutely positioned children.', 1),
  ('bld-q44', 'What does "position: absolute" position an element relative to?', '["The browser window only","Its nearest positioned ancestor (one with relative, absolute, or fixed positioning), or the page if none exists","Always the body element","The mouse cursor"]', 1, 'Absolutely positioned elements are placed relative to the closest ancestor that has a position other than static; if none exists, it uses the initial containing block.', 2),
  ('bld-q44', 'How does "position: fixed" behave when the page is scrolled?', '["It scrolls away with the rest of the content","It stays in the same place on the screen, even as the page scrolls","It disappears when scrolling starts","It moves faster than the rest of the page"]', 1, 'Fixed positioning anchors an element to the viewport, so it remains visibly "stuck" in place regardless of scrolling — useful for sticky headers.', 3),
  ('bld-q44', 'What is special about "position: sticky"?', '["It behaves like relative positioning until a scroll threshold is reached, then sticks like fixed","It always behaves exactly like absolute","It removes the element from the page","It only works on images"]', 0, 'Sticky elements scroll normally with the page until they reach a specified offset, then "stick" in place within their container, combining relative and fixed behavior.', 4),
  ('bld-q44', 'If a parent has "position: relative" and a child has "position: absolute; top: 0; left: 0;", where does the child appear?', '["At the top-left corner of the browser window","At the top-left corner of the relatively positioned parent","Centered on the page","It disappears"]', 1, 'Because the parent is a positioned ancestor, the absolutely positioned child is placed relative to that parent''s box, not the whole page.', 5),
  ('bld-q44', 'What does the "z-index" property control when using positioned elements?', '["The element''s width","The stacking order — which elements appear in front of or behind others","The element''s font size","The page''s background color"]', 1, 'Z-index determines the stacking order of overlapping positioned elements; higher values appear on top of lower values.', 6),
  ('bld-q44', 'Why does z-index only work on elements with a position value other than "static" (the default)?', '["It is a rule browsers enforce because stacking context is tied to positioned elements","z-index actually works on every element including static ones","z-index is unrelated to positioning","Static elements cannot be displayed at all"]', 0, 'By CSS specification, z-index only has an effect on positioned elements (relative, absolute, fixed, or sticky) — static elements ignore it.', 7),
  ('bld-q44', 'What is a common real-world use of "position: sticky" on a webpage?', '["Making a table of contents or navigation bar stay visible while scrolling through a section","Deleting elements after scrolling","Centering text horizontally","Changing image file formats"]', 0, 'Sticky positioning is often used for navigation menus or sidebars that should stay visible as the user scrolls through related content.', 8),
  ('bld-q44', 'If two absolutely positioned elements overlap and you want one specific one on top, what should you adjust?', '["Their font sizes","Their z-index values, giving the desired element a higher number","Their text color","Their alt text"]', 1, 'Adjusting z-index lets you control which overlapping element visually appears above the other.', 9),
  ('bld-q44', 'What happens to the normal page flow when an element is set to "position: absolute"?', '["It is removed from the normal flow, so other elements act as if it isn''t there","Nothing changes about the flow","All sibling elements are deleted","The page flow reverses direction"]', 0, 'Absolutely positioned elements are taken out of the normal document flow, meaning surrounding elements collapse or shift as if that element doesn''t take up space.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q45: CSS Gradients Advanced Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q45', 'What does "radial-gradient" create, compared to "linear-gradient"?', '["A gradient that radiates outward from a center point, instead of going in a straight line","The exact same effect as linear-gradient","A solid color only","A gradient that only works on text"]', 0, 'Radial gradients spread color outward from a focal point in circular or elliptical rings, unlike linear gradients which move in a straight line direction.', 1),
  ('bld-q45', 'In "linear-gradient(45deg, red, blue)", what does the 45deg control?', '["The transparency level","The angle/direction the gradient flows across the element","The size of the element","The number of colors used"]', 1, 'The angle value sets the direction the gradient travels, with 45deg pointing diagonally from bottom-left to top-right.', 2),
  ('bld-q45', 'What does adding a percentage to a gradient color stop do, like "linear-gradient(red 0%, blue 80%)"?', '["It controls where each color starts and ends along the gradient","It changes the element''s width","It rotates the element","It has no effect at all"]', 0, 'Color stop percentages let you control exactly where colors begin transitioning, allowing precise control over the gradient''s appearance.', 3),
  ('bld-q45', 'How can you create a gradient with more than two colors?', '["Gradients can only ever have two colors","List additional colors separated by commas, like linear-gradient(red, yellow, blue)","Use two separate background properties","Use the \"multi-gradient\" property"]', 1, 'CSS gradients support multiple color stops; simply list more colors separated by commas to create a multi-color blend.', 4),
  ('bld-q45', 'What is "repeating-linear-gradient" used for?', '["Creating a gradient pattern that repeats over and over, like stripes","Making a gradient that fades to transparent only once","Repeating an image as a background","Disabling gradients entirely"]', 0, 'Repeating-linear-gradient tiles the gradient pattern repeatedly across the element, which is great for creating striped or patterned backgrounds.', 5),
  ('bld-q45', 'Can you use "rgba()" or transparency values inside a gradient, like "linear-gradient(rgba(255,0,0,0), blue)"?', '["No, gradients only accept solid hex colors","Yes, gradients can use rgba() so colors fade into transparency","Transparency is only allowed in radial gradients","Gradients ignore alpha values"]', 1, 'Gradients fully support rgba() and other color formats with transparency, which is often used to fade a color into "nothing" for overlay effects.', 6),
  ('bld-q45', 'What is a practical use of a gradient overlay on a background image?', '["Darkening part of an image so white text remains readable on top of it","Deleting the image entirely","Making the image load faster","Changing the image file format"]', 0, 'A common design technique layers a semi-transparent gradient over a photo so text placed on top stays legible against varying image brightness.', 7),
  ('bld-q45', 'In "radial-gradient(circle at top left, yellow, orange)", what does "at top left" control?', '["The size of the gradient","The position of the gradient''s center point","The rotation angle","The number of colors"]', 1, 'The "at" keyword positions the radial gradient''s focal point; here it starts radiating from the top-left corner of the element.', 8),
  ('bld-q45', 'Why might a developer use "conic-gradient" instead of linear or radial?', '["Conic gradients rotate colors around a center point, useful for things like pie charts or color wheels","Conic gradients are identical to linear gradients","Conic gradients can only use one color","Conic gradients are not valid CSS"]', 0, 'Conic gradients sweep colors around a center point like a clock hand, making them ideal for pie-chart-style visuals or color wheel effects.', 9),
  ('bld-q45', 'If you want a smooth sunset effect transitioning from orange at the top to purple at the bottom, what should you use?', '["linear-gradient(to bottom, orange, purple)","radial-gradient(circle, orange)","A single solid background-color","border-gradient property"]', 0, 'A linear gradient going "to bottom" with orange transitioning to purple creates a smooth top-to-bottom color blend, perfect for a sunset effect.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q46: HTML Semantic Review Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q46', 'What does "semantic HTML" mean?', '["HTML written in a foreign language","HTML elements that describe the meaning of their content, not just its appearance","HTML that uses only divs and spans","HTML that has no CSS attached"]', 1, 'Semantic HTML uses tags that clearly describe the type of content they hold, like <article> or <nav>, instead of generic containers with no meaning.', 1),
  ('bld-q46', 'Which tag should you use for the main navigation links of a website?', '["<nav>","<div>","<span>","<header>"]', 0, 'The <nav> element is specifically meant to wrap a website''s primary navigation links, helping browsers and screen readers identify it.', 2),
  ('bld-q46', 'Which tag is best for wrapping a self-contained piece of content, like a blog post or news story?', '["<aside>","<article>","<footer>","<br>"]', 1, '<article> represents independent, self-contained content that could stand alone, such as a blog post, news article, or forum post.', 3),
  ('bld-q46', 'What is the <aside> tag typically used for?', '["The main page content","Content tangentially related to the main content, like a sidebar or pull quote","The page footer only","Form input fields"]', 1, '<aside> marks content that is related but separate from the main flow, such as sidebars, advertisements, or extra tips.', 4),
  ('bld-q46', 'Why is using <header> and <footer> better than using generic <div> tags for those sections?', '["It has no real benefit","It gives meaning to assistive technologies and search engines about the page structure","It makes the page load slower","Div tags cannot be used at the top or bottom of a page"]', 1, 'Semantic tags like <header> and <footer> communicate structure to screen readers and search engines, improving accessibility and SEO.', 5),
  ('bld-q46', 'Which tag represents the dominant, unique content of a webpage (used only once per page)?', '["<section>","<main>","<div>","<span>"]', 1, 'The <main> element should wrap the primary unique content of the page and should be used only once, helping screen reader users skip directly to it.', 6),
  ('bld-q46', 'What is the difference between <section> and <div>?', '["There is no difference at all","<section> represents a thematic grouping of content with semantic meaning, while <div> is a generic container with none","<div> can only hold text","<section> cannot contain images"]', 1, '<section> groups related content thematically and adds meaning to the document outline, whereas <div> is purely a generic, meaningless wrapper.', 7),
  ('bld-q46', 'Why do screen readers benefit from semantic HTML tags like <nav>, <main>, and <article>?', '["They allow users to quickly jump between meaningful sections of a page instead of reading everything line by line","Screen readers ignore semantic tags completely","Semantic tags slow down screen readers","They only help with images, not text"]', 0, 'Semantic tags create landmarks that screen reader users can jump between, making navigation through a page far more efficient and accessible.', 8),
  ('bld-q46', 'Which is the most semantically correct way to mark up a list of blog post previews on a homepage?', '["A series of <div> tags with no other markup","A series of <article> elements, each representing one blog post preview","One giant <span> wrapping everything","Using only <br> tags between posts"]', 1, 'Each blog post preview is independent, self-contained content, making <article> the most semantically appropriate choice for each one.', 9),
  ('bld-q46', 'If you wanted to mark up a website footer containing copyright info and social links, which tag is most appropriate?', '["<footer>","<header>","<nav> only","<aside> only"]', 0, 'The <footer> tag is designed specifically for footer content like copyright notices, contact info, and related links at the bottom of a page or section.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q47: CSS Filters Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q47', 'What does the CSS "filter" property do?', '["Filters out unused CSS code","Applies visual effects like blur, brightness, or grayscale to an element","Removes elements from the page","Filters form input values"]', 1, 'The filter property applies graphical effects directly in CSS, such as blurring, adjusting brightness, or converting an image to grayscale.', 1),
  ('bld-q47', 'What does "filter: grayscale(100%)" do to an image?', '["Makes the image completely transparent","Removes all color, turning the image black and white","Doubles the image size","Rotates the image 100 degrees"]', 1, 'grayscale(100%) fully desaturates the image, converting it entirely to shades of gray, similar to an old black-and-white photo.', 2),
  ('bld-q47', 'What does "filter: blur(5px)" do?', '["Sharpens the image","Softens and blurs the image by the given pixel radius","Crops the image by 5 pixels","Changes the image''s file format"]', 1, 'The blur filter softens an element''s appearance, with a larger pixel value creating a stronger blur effect.', 3),
  ('bld-q47', 'What does "filter: brightness(150%)" do compared to the original image?', '["Makes the image 150% larger in size","Makes the image appear brighter than normal","Makes the image 150% darker","Removes the image entirely"]', 1, 'Brightness values above 100% make the image lighter/brighter than its original appearance, while values below 100% darken it.', 4),
  ('bld-q47', 'Can multiple filters be combined on the same element, like "filter: blur(2px) grayscale(50%)"?', '["No, only one filter function can be used at a time","Yes, multiple filter functions can be chained together, separated by spaces","Filters can only be combined using JavaScript","Combining filters crashes the browser"]', 1, 'CSS allows chaining multiple filter functions together in a single declaration, applying all the effects in combination.', 5),
  ('bld-q47', 'What does "filter: sepia(100%)" do to an image?', '["Gives it a warm, brownish vintage tone, like old photographs","Makes the image completely invisible","Sharpens fine details","Inverts all colors"]', 0, 'Sepia applies a warm brown tone reminiscent of old-fashioned photographs, often used for vintage or nostalgic visual styling.', 6),
  ('bld-q47', 'What does "filter: invert(100%)" do to an image''s colors?', '["Leaves colors unchanged","Flips each color to its opposite on the color wheel, like a photo negative","Makes the image black only","Removes the image''s background"]', 1, 'Invert flips all colors to their opposites, creating a negative-like effect, similar to how old camera film negatives looked.', 7),
  ('bld-q47', 'Why might a designer apply "filter: brightness(50%)" to a background image behind white text?', '["To make the background darker so the white text is easier to read","To delete the background image","To make the text invisible","To change the image file size"]', 0, 'Darkening a background image with reduced brightness increases contrast with light-colored text, improving readability.', 8),
  ('bld-q47', 'Is CSS "filter" commonly used to create hover effects, like an image that becomes grayscale until you hover over it?', '["No, filters cannot respond to hover at all","Yes, combining filter with the :hover pseudo-class is a common interactive design technique","Filters only work on page load and never change","Hover effects require deleting the filter property"]', 1, 'Pairing filter with :hover lets designers create interactive effects, such as an image starting grayscale and becoming full-color on mouse hover.', 9),
  ('bld-q47', 'What is the default (unfiltered) value of most CSS filter functions, like blur(0) or grayscale(0%)?', '["The element disappears completely","The element looks the same as if no filter were applied at all","The element becomes fully transparent","The element''s size doubles"]', 1, 'A filter value of zero (or 0%) typically means no visible effect is applied, leaving the element looking like its original, unfiltered self.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q48: Web Fundamentals Review Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q48', 'What is the main purpose of HTML on a webpage?', '["To style colors and fonts","To provide the structure and content of a webpage","To make the website run faster","To store user passwords"]', 1, 'HTML (HyperText Markup Language) defines the structure and content of a webpage, like headings, paragraphs, images, and links.', 1),
  ('bld-q48', 'What is the main purpose of CSS on a webpage?', '["To structure content with headings and paragraphs","To style and visually design the webpage, like colors, fonts, and layout","To handle user logins","To connect to a database"]', 1, 'CSS (Cascading Style Sheets) controls the visual presentation of a webpage, including colors, fonts, spacing, and layout.', 2),
  ('bld-q48', 'Which HTML tag is used to create a hyperlink to another page?', '["<img>","<a>","<p>","<div>"]', 1, 'The anchor tag <a>, typically with an "href" attribute, creates clickable links to other pages or resources.', 3),
  ('bld-q48', 'What does the "alt" attribute on an <img> tag provide?', '["A backup image if the first fails to load only","A text description of the image for accessibility and for when the image fails to load","The image''s file size","The image''s color palette"]', 1, 'The alt attribute provides alternative text describing the image, which is read aloud by screen readers and shown if the image cannot load.', 4),
  ('bld-q48', 'In CSS, what does "color: blue;" do versus "background-color: blue;"?', '["They do the exact same thing","\"color\" changes text color, while \"background-color\" changes the element''s background fill","background-color changes text only","color only works on images"]', 1, '"color" sets the color of text content, while "background-color" fills the element''s background area, two different visual properties.', 5),
  ('bld-q48', 'What is the CSS box model made up of?', '["Only width and height","Content, padding, border, and margin","Only color and font","HTML tags only"]', 1, 'The box model describes how every element''s size is calculated: the content area, surrounded by padding, then border, then margin.', 6),
  ('bld-q48', 'Which CSS selector targets all elements with class="highlight"?', '["#highlight","highlight",".highlight","*highlight"]', 2, 'A period (.) before a name selects all elements with that class, so ".highlight" targets every element with class="highlight".', 7),
  ('bld-q48', 'Which CSS selector targets the single element with id="main-title"?', '[".main-title","#main-title","main-title","*main-title"]', 1, 'A hash (#) before a name selects the element with that specific id, and ids should be unique within a page.', 8),
  ('bld-q48', 'What does "display: flex;" help you do in CSS?', '["Hide an element completely","Easily arrange child elements in flexible rows or columns for layout","Change text to bold","Add a background image"]', 1, 'Flexbox (display: flex) is a layout system that makes it easy to align and distribute child elements along a row or column.', 9),
  ('bld-q48', 'Why is it important to write valid, well-structured HTML even though browsers often try to fix mistakes?', '["It is not important since browsers always fix every mistake perfectly","Valid HTML ensures consistent rendering across browsers and better accessibility for all users","Browsers refuse to display invalid HTML at all","Validity only matters for CSS, not HTML"]', 1, 'While browsers are forgiving, valid and well-structured HTML renders more predictably across different browsers and works better with assistive technology.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q49: Builders Mid-Point Review Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q49', 'In Scratch, what does "broadcast" allow sprites to do?', '["Send messages to each other so they can react to the same event","Only play music","Delete each other","Change the project''s language"]', 0, 'Broadcasting lets one sprite send a signal that any other sprite can listen for and react to, enabling coordinated multi-sprite behavior.', 1),
  ('bld-q49', 'Which HTML tag should you use to create a numbered list?', '["<ul>","<ol>","<li> alone","<table>"]', 1, '<ol> creates an ordered (numbered) list, while <ul> creates an unordered (bulleted) list; both use <li> for individual items.', 2),
  ('bld-q49', 'In Scratch, what is a "clone" used for?', '["Permanently deleting a sprite","Creating a temporary copy of a sprite that can run its own scripts, useful for things like multiple enemies or bullets","Renaming a sprite","Changing a sprite''s costume permanently"]', 1, 'Clones are dynamic copies of a sprite created while the program runs, often used to generate many similar objects like enemies or projectiles.', 3),
  ('bld-q49', 'What does the CSS property "border-radius" do?', '["Changes text size","Rounds the corners of an element''s box","Changes the page''s background image","Adds a shadow effect"]', 1, 'border-radius rounds the corners of an element, and a large enough value (like 50%) can turn a square into a circle.', 4),
  ('bld-q49', 'In Scratch, which block would you use to make a sprite ask the player a question and store their typed response?', '["say","ask and wait","broadcast","wait"]', 1, '"Ask and wait" displays a question with a text input box and stores the player''s typed response in the "answer" variable.', 5),
  ('bld-q49', 'What is the purpose of the "alt" attribute on an HTML <img> tag?', '["To resize the image","To describe the image for screen readers and for when the image fails to load","To change the image''s color","To add a clickable link"]', 1, 'Alt text provides a description of an image for accessibility purposes and as a fallback if the image cannot be displayed.', 6),
  ('bld-q49', 'In Scratch, what is the difference between a costume change and a position change for a sprite?', '["They are the same thing","Costume changes alter how the sprite looks, while position changes move it on the stage","Costume changes move the sprite, position changes alter appearance","Neither has a visible effect"]', 1, 'Costumes control a sprite''s visual appearance (like animation frames), while x/y position blocks control where it is located on the stage.', 7),
  ('bld-q49', 'Which CSS property would you use to make text bold?', '["text-decoration: underline;","font-weight: bold;","color: bold;","text-align: bold;"]', 1, 'font-weight: bold; makes text appear thicker and more prominent, which is the correct property for bold styling.', 8),
  ('bld-q49', 'In a Scratch quiz game, what variable does Scratch automatically use to store what the player types after "ask and wait"?', '["score","answer","response","input"]', 1, 'Scratch has a built-in variable called "answer" that automatically stores whatever text the player types in response to an "ask and wait" block.', 9),
  ('bld-q49', 'Which semantic HTML tag is best for wrapping the main navigation menu of a website?', '["<div>","<nav>","<span>","<aside>"]', 1, 'The <nav> tag is specifically designed to mark up a section of primary navigation links, improving both structure and accessibility.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Q50: Builders Final Assessment Quiz
-- =============================================================================
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, sort_order)
SELECT q.id, qq.question, qq.options::jsonb, qq.correct_answer, qq.explanation, 10, qq.sort_order
FROM quizzes q, (VALUES
  ('bld-q50', 'What is the main purpose of the "alt" attribute on images in HTML?', '["To make images load faster","To describe the image for screen readers and accessibility, and as a fallback if the image fails to load","To change the image''s size automatically","To add a border around the image"]', 1, 'Alt text is essential for accessibility, allowing screen reader users to understand image content, and it displays as a fallback when images fail to load.', 1),
  ('bld-q50', 'In Scratch, what does broadcasting a message let multiple sprites do?', '["Delete each other automatically","React to the same event at the same time, even though they are separate sprites","Merge into a single sprite","Change the project''s title"]', 1, 'Broadcasting allows separate sprites to listen for and respond to the same signal, enabling coordinated actions across a whole project.', 2),
  ('bld-q50', 'Which CSS property controls the spacing INSIDE an element, between its content and its border?', '["margin","padding","border-radius","z-index"]', 1, 'Padding adds space between an element''s content and its border, while margin adds space outside the border between elements.', 3),
  ('bld-q50', 'Why is using semantic HTML tags like <main>, <nav>, and <article> important for accessibility?', '["They have no impact on accessibility","They help screen readers and assistive technology understand and navigate page structure more easily","They only affect how fast a page loads","They are purely decorative"]', 1, 'Semantic tags create meaningful landmarks that screen readers can use to help users navigate and understand a page''s structure efficiently.', 4),
  ('bld-q50', 'In Scratch, what is a "clone" primarily useful for?', '["Permanently changing the original sprite''s code","Creating temporary copies of a sprite at runtime, useful for things like multiple enemies, bullets, or particles","Recording sound effects","Translating the project into other languages"]', 1, 'Clones let one sprite''s code generate many dynamic copies while the program runs, which is efficient for repeated game elements.', 5),
  ('bld-q50', 'What does responsible "digital citizenship" mean when sharing a Scratch project online?', '["Sharing anything without thinking about others","Being kind, respectful, and safe online — like not sharing personal information and giving credit for remixed work","Only sharing projects with strangers","Avoiding all online communication"]', 1, 'Digital citizenship includes being respectful and safe online, such as protecting personal information and properly crediting work you build on or remix.', 6),
  ('bld-q50', 'Why might a developer combine CSS "filter: blur()" with a ":hover" effect on an image gallery?', '["To permanently delete images on hover","To create an interactive effect where an image sharpens or changes appearance when a user hovers over it","Filters cannot be combined with hover","To make text bold"]', 1, 'Combining filters with :hover is a common way to create engaging interactive effects, such as an image transitioning from blurred to sharp.', 7),
  ('bld-q50', 'In a Scratch platform game, what is gravity usually simulated with?', '["A constant value that pulls the sprite''s y-position downward each frame unless something stops it","Changing the sprite''s costume color","The \"ask and wait\" block","Deleting and recreating the sprite"]', 0, 'Gravity in platformers is typically coded as a steady downward force applied to vertical position or velocity each frame, creating realistic falling motion.', 8),
  ('bld-q50', 'Why is it good practice to provide text alternatives (like alt text or captions) for non-text content on websites and in projects?', '["It is not necessary if the content looks nice","It ensures people using screen readers or who cannot see images can still understand and access the content","It only matters for videos, not images","It slows down the website unnecessarily"]', 1, 'Providing text alternatives ensures that everyone, including users relying on screen readers, can access and understand the content, which is a core accessibility principle.', 9),
  ('bld-q50', 'Which best summarizes the relationship between HTML, CSS, and Scratch as tools you have learned in Builders?', '["They are unrelated and never used together","HTML structures content, CSS styles its appearance, and Scratch teaches programming logic visually — all are different ways to build interactive creations","CSS replaces HTML entirely","Scratch is only for younger kids and not real coding"]', 1, 'HTML and CSS work together to build and style websites, while Scratch introduces core programming logic (loops, conditionals, events) in a visual format — together they build a strong coding foundation.', 10)
) AS qq(quiz_slug, question, options, correct_answer, explanation, sort_order)
WHERE q.slug = qq.quiz_slug
ON CONFLICT DO NOTHING;
</content>
